services:
  web:
    build: .
    command: fastapi run src/main.py
    ports:
      - "8001:8000"
    volumes:
      - .:/app/
    depends_on:
      - database

  database:
    image: postgres:17-alpine3.21
    env_file: .env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: