"""empty message

Revision ID: 3ea26c130255
Revises: 0440077b9f8e
Create Date: 2025-06-09 16:40:29.931898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ea26c130255'
down_revision: Union[str, None] = '0440077b9f8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet_info', sa.Column('wallet_address', sa.String(), nullable=False))
    op.add_column('wallet_info', sa.Column('bandwidth_limit', sa.Integer(), nullable=False))
    op.add_column('wallet_info', sa.Column('bandwidth_left', sa.Integer(), nullable=False))
    op.add_column('wallet_info', sa.Column('energy_limit', sa.Integer(), nullable=False))
    op.add_column('wallet_info', sa.Column('energy_left', sa.Integer(), nullable=False))
    op.alter_column('wallet_info', 'balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=4),
               existing_nullable=False)
    op.drop_column('wallet_info', 'balance_id')
    op.drop_column('wallet_info', 'energy')
    op.drop_column('wallet_info', 'bandwidth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet_info', sa.Column('bandwidth', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('wallet_info', sa.Column('energy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('wallet_info', sa.Column('balance_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('wallet_info', 'balance',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('wallet_info', 'energy_left')
    op.drop_column('wallet_info', 'energy_limit')
    op.drop_column('wallet_info', 'bandwidth_left')
    op.drop_column('wallet_info', 'bandwidth_limit')
    op.drop_column('wallet_info', 'wallet_address')
    # ### end Alembic commands ###
